_target_: flash.core.trainer.Trainer

gpus: -1

min_epochs: 1
max_epochs: 100

# number of validation steps to execute at the beginning of the training
# num_sanity_val_steps: 0

# ckpt path
resume_from_checkpoint: null
