_target_: src.datamodules.flash_object_detection_data_module.FlashObjectDetectionData

data_dir: ${data_dir} # data_dir is specified in config.yaml
batch_size: 64
val_split: 0.1
transform_kwargs: { "image_size": 512 }
