_target_: src.datamodules.flash_object_detection_data_module.FlashObjectDetectionData
#_target_: flash.image.detection.data.ObjectDetectionData.from_coco

train_folder: ${data_dir}venus/images/train/
train_ann_folder: ${data_dir}venus/annotations/train/
test_folder: ${data_dir}venus/images/test/
test_ann_folder: ${data_dir}venus/annotations/test/
transform_kwargs: { "image_size": 640 }
labels: ['venus']
pin_memory: True
num_workers: 4
val_split: 0.1
batch_size: 32
