_target_: src.datamodules.flash_object_detection_data_module.FlashObjectDetectionData
#_target_: flash.image.detection.data.ObjectDetectionData.from_coco

train_folder: ${data_dir}coco/images/train/
train_ann_file: ${data_dir}coco/annotations/train/
test_folder: ${data_dir}coco/images/test/
test_ann_file: ${data_dir}coco/annotations/test/
transform_kwargs: { "image_size": 640 }
batch_size: 32
